# Generated by Django 5.2.7 on 2026-01-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_recipe_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
